=== DavidHS123/ASIX-M04XML/XML/Tasca11/enciclopedia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="enciclopedia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="cognom" type="xs:string"/>
                            <xs:element name="publicacio" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="datanaixement" type="xs:date"/>
                        <xs:attribute name="sexe">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="H"/>
                                    <xs:enumeration value="D"/>
                                    <xs:enumeration value="I"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DavidHS123/ASIX-M04XML/XML/Tasca11/enciclopedia.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<enciclopedia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="enciclopedia.xsd">
<persona datanaixement="1942-01-08" sexe="I"> 
    <nom>Stephen</nom> 
    <cognom>HAWKING</cognom> 
    <publicacio>Una breu historia del temps</publicacio>
</persona>
<persona datanaixement="1942-01-08" sexe="I">
    <nom>Hubert</nom>
    <cognom>HAWKING</cognom>
        <publicacio>L'Univers explicat als infants</publicacio>
        <publicacio>L'evolucio cosmica</publicacio>
        <publicacio>Pols d'estrelles</publicacio>
</persona>
<persona datanaixement="1879-01-08" sexe="I">
    <nom>Albert</nom>
    <cognom>Einstein</cognom>
    <publicacio>Les ones gravitacionals</publicacio>
    <publicacio>Sobre la teoria cuantica de la llum</publicacio>
</persona>
<persona datanaixement="1867-01-08" sexe="D">
    <nom>Marie</nom>
    <cognom>CURIE</cognom>
    <publicacio>Tractat de radioactivitat</publicacio>
</persona>
</enciclopedia>
