=== DavidHS123/ASIX-M04XML/XML/Factura XML/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="NIFType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Za-z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CIFType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[ABCDEFGHJKLMNPQRSUVW]\d{7}[0-9A-J]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CognomType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="numfactura" type="xs:integer" />
                <xs:element name="data" type="xs:date" />
                <xs:element name="logo" type="xs:string" />
                <xs:element name="dadesemissor" type="DadesEmissorType" />
                <xs:element name="dadesreceptor" type="DadesReceptorType" />
                <xs:element name="resumfactura" type="xs:string" />
                <xs:element name="periodesconsum" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="missagepublicitari">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="300" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="pagament" type="PagamentType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DadesEmissorType">
        <xs:sequence>
            <xs:element name="nom" type="xs:string" />
            <xs:element name="cognom" type="CognomType" minOccurs="1" maxOccurs="2" />           
            <xs:element name="adreça" type="AdreçaType" />
            <xs:element name="telefon" type="TelefonType" minOccurs="0" />
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="cif" type="CIFType" />
    </xs:complexType>

    <xs:complexType name="DadesReceptorType">
        <xs:sequence>
            <xs:element name="nom" type="xs:string" />
            <xs:element name="cognom" type="CognomType" minOccurs="1" maxOccurs="2" />
            <xs:element name="adreça" type="AdreçaType" />
            <xs:element name="telefon" type="TelefonType" minOccurs="0" />
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="nif" type="NIFType" />
    </xs:complexType>

    <xs:complexType name="AdreçaType">
        <xs:sequence>
            <xs:element name="carrer" type="xs:string" />
            <xs:element name="numero" type="xs:string" />
            <xs:element name="pis" type="xs:string" minOccurs="0" />
            <xs:element name="porta" type="xs:string" minOccurs="0" />
            <xs:element name="cp" type="xs:integer" />
            <xs:element name="ciutat" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PagamentType">
        <xs:sequence>
            <xs:element name="iban" type="xs:string" minOccurs="0" />
            <xs:element name="targeta" type="TargetaType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="quantitat" type="xs:decimal" />
        <xs:attribute name="estat" type="EstatType" />
        <xs:attribute name="metodopagament" type="MetodePagamentType" />
    </xs:complexType>

    <xs:complexType name="TargetaType">
        <xs:sequence>
            <xs:element name="numero" type="xs:string" />
            <xs:element name="nom" type="xs:string" />
            <xs:element name="cognom" type="xs:string" />
            <xs:element name="datacaducitat" type="xs:string" />
            <xs:element name="cvv" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EstatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pendent" />
            <xs:enumeration value="pagada" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MetodePagamentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Comptat" />
            <xs:enumeration value="Transferència" />
            <xs:enumeration value="Targeta" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TelefonType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]*" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DavidHS123/ASIX-M04XML/XML/Factura XML/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura.xsd">
    <numfactura>123</numfactura>
    <data>2023-12-15</data>
    <logo>http://exemple.com/logo.png</logo>
    
    <dadesemissor nif="12345678A">
        <nom>Empresa ABC</nom>
        <cognom>Cognom Emissor</cognom>
        <adreça>
            <carrer>Carrer Emissor</carrer>
            <numero>123</numero>
            <poblacio>Població Emissor</poblacio>
        </adreça>
        <telefon>123456789</telefon>
        <email>emissor@exemple.com</email>
    </dadesemissor>
    
    <dadesreceptor cif="A12345678">
        <nom>Client XYZ</nom>
        <cognom>Cognom Receptor</cognom>
        <adreça>
            <carrer>Carrer Receptor</carrer>
            <numero>456</numero>
            <pis>Pis</pis>
            <porta>5</porta>
            <cp>17000</cp>
            <ciutat>Girona</ciutat>
        </adreça>
        <telefon>987654321</telefon>
        <email>receptor@exemple.com</email>
    </dadesreceptor>
    
    <resumfactura>Resum de la factura...</resumfactura>
    
    <periodesconsum>
        Gener 2023
    </periodesconsum>
    <periodesconsum>
        Febrer 2023
    </periodesconsum>
    <periodesconsum>
        Març 2023
    </periodesconsum>
    <periodesconsum>
        Abril 2023
    </periodesconsum>
    
    <missagepublicitari>Missatge publicitari aquí...</missagepublicitari>
    
    <productes>
        <producte>
            <nom>Producte 1</nom>
            <quantitat>2</quantitat>
            <preu>20.50</preu>
        </producte>
        <!-- Altres productes aquí -->
    </productes>
    
    <resum quantitat="150.75" estat="pagada" metodopagament="Transferència">
        <iban>CAT1234567890123456789</iban>
    </resum>
</factura>
