=== DavidHS123/ASIX-M04XML/XML/Tasca9/Exercici1/validacio.dtd
<!ELEMENT persones (persona+)>
<!ELEMENT persona (nif, nom, cognom1, cognom2, adreca, datanaixement, correu*, telefon*, foto?, observacions*, contacte)>
    <!ATTLIST persona estatcivil (solter | casat | soltera | casada) #REQUIRED
                      situaciolaboral (actiu | aturat | activa | aturada) #IMPLIED>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom1 (#PCDATA)>
<!ELEMENT cognom2 (#PCDATA)>
<!ELEMENT adreca (carrer, num, poblacio)>
    <!ATTLIST adreca tipusadreca (domicili | feina) "domicili">
<!ELEMENT carrer (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT poblacio (#PCDATA)>
<!ELEMENT datanaixement (any, mes, dia)>
    <!ELEMENT any (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
<!ELEMENT correu (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
    <!ATTLIST telefon tipus (mobil | fix) #IMPLIED>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT observacions (#PCDATA)>
<!ELEMENT contacte (telefon*, correu*)>

=== DavidHS123/ASIX-M04XML/XML/Tasca9/Exercici1/Tasca9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persones SYSTEM "validacio.dtd">
<persones>
    <persona estatcivil="solter" situaciolaboral="aturat">
        <nif>5211926735E</nif>
        <nom>David</nom>
        <cognom1>Hidalgo</cognom1>
        <cognom2>Salinas</cognom2>
        <adreca tipusadreca="domicili">
            <carrer>Dolors Callol</carrer>
            <num>5</num>
            <poblacio>Breda</poblacio>
        </adreca>
        <datanaixement>
            <any>2005</any>
            <mes>desembre</mes>
            <dia>20</dia>
        </datanaixement>
        <correu>correuexemple@exemple.com</correu>
        <telefon>999 99 99 99</telefon>
        <foto>www.urlfoto.cat</foto>
        <observacions>Aqui especifiquem les observacions que vulguem.</observacions>
        <contacte>
            <telefon>999 99 99 99</telefon>
            <correu>correucontacte@exemple.com</correu>
        </contacte>
    </persona>
    <persona estatcivil="casada" situaciolaboral="actiu">
        <nif>123456789A</nif>
        <nom>Anna</nom>
        <cognom1>Pérez</cognom1>
        <cognom2>Martínez</cognom2>
        <adreca tipusadreca="feina">
            <carrer>Gran Via</carrer>
            <num>123</num>
            <poblacio>Barcelona</poblacio>
        </adreca>
        <datanaixement>
            <any>1980</any>
            <mes>gener</mes>
            <dia>15</dia>
        </datanaixement>
        <correu>anna.perez@example.com</correu>
        <telefon>555 55 55 55</telefon>
        <observacions>És una persona molt amable.</observacions>
        <contacte>
            <telefon>555 55 55 55</telefon>
            <correu>anna.contacte@example.com</correu>
        </contacte>
    </persona>
</persones>
